{% set name = "gwf" %}
{% set version = "1.8.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - attrs
    - click
    - click-plugins
    - pip
    - flit
    - python>=3.7
    - importlib_metadata
  run:
    - attrs
    - click
    - click-plugins
    - python>=3.7
    - importlib_metadata

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help

about:
  home: http://gwf.app/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: A flexible, pragmatic workflow tool.
  doc_url: https://gwf.app/
  dev_url: https://github.com/gwforg/gwf

extra:
  recipe-maintainers:
    - dansondergaard
