name: Build docs and push to docs branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and push docs
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip nox
        shell: bash

      - name: Build docs
        run: |
          python -m nox -s docs
        shell: bash

      - name: Push to docs branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:gwforg/gwforg.github.io.git
          BRANCH: main
          FOLDER: docs/_build/dirhtml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
