name: Build and deploy docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and push docs
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip nox
        shell: bash

      - name: Build docs
        run: |
          python -m nox -s docs
        shell: bash

      - name: Add .nojekyll
        run: |
          touch docs/_build/dirhtml/.nojekyll
        shell: bash

      - name: Add CNAME file
        run: |
          echo gwf.app > docs/_build/dirhtml/CNAME
        shell: bash

      - name: Push to docs branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:gwforg/gwforg.github.io.git
          BRANCH: main
          FOLDER: docs/_build/dirhtml
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
