name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Extract changes for this release
        run: cat CHANGELOG.rst | python extract-changelog.py ${{ github.ref_name }} > /tmp/changelog.md

      - name: Release
        uses: softprops/action-gh-release@v1
