name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-10.15", "ubuntu-20.04"]
        python_version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip nox
      shell: bash

    - name: Run tests
      run: |
        python -m nox -s test-${{ matrix.python_version }}
      shell: bash

    - name: Submit partial coverage results
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.python_version }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-20.04

    steps:
    - name: Submit complete coverage results
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install gwf
        run: |
          python -m pip install --upgrade pip flit
          flit install -s
      - name: Lint
        run: nox --non-interactive -s lint

  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install gwf
        run: |
          python -m pip install --upgrade pip flit
          flit install -s
      - name: Build docs
        run: nox --non-interactive -s docs
